name: fastapidozero
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.0
    - uvicorn==0.24.0
    - pytest==7.4.3
    - httpx==0.25.0
    - SQLAlchemy==2.0.31
    - psycopg2==2.9.9